services:
    - type: web
      region: ohio
      name: lalydaycare
      env: python
      buildCommand: "./render_build.sh"
      startCommand: "gunicorn wsgi --chdir ./src/"
      plan: free
      numInstances: 1
      envVars:
          - key: BASENAME
            value: /
          - key: FLASK_APP
            value: src/app.py
          - key: FLASK_DEBUG
            value: 0
          - key: FLASK_APP_KEY
            value: "any key works"
          - key: PYTHON_VERSION
            value: 3.10.6
          - key: DATABASE_URL
            value: "postgresql://laury_rbpw_user:VwzSZwqAdeqBx60QIrpwdEKdao8odKy4@dpg-cut2nutumphs73ceq59g-a.oregon-postgres.render.com/laury_rbpw" # Cambia esto por tu URL de conexión real

# No es necesario agregar la configuración de la base de datos si la base de datos es externa
# databases:
#     - name: postgresql-trapezoidal-42170
#       region: ohio
#       ipAllowList: []
#       plan: free
