"""empty message

Revision ID: 06d22ba04365
Revises: e1534138f638
Create Date: 2025-01-23 16:46:37.743338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d22ba04365'
down_revision = 'e1534138f638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventsuscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('events_selection', sa.String(length=120), nullable=False),
    sa.Column('parent_name', sa.String(length=120), nullable=False),
    sa.Column('special_request', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('events_selection', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('parent_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('special_request', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.drop_table('eventsuscriptions')
    # ### end Alembic commands ###
