"""empty message

Revision ID: 338db53d4fe4
Revises: 4ea434efea85
Create Date: 2025-01-13 00:23:39.928119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338db53d4fe4'
down_revision = '4ea434efea85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
