"""empty message

Revision ID: 8aae38436ee5
Revises: 6aaecffa0437
Create Date: 2025-02-14 15:33:54.704335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aae38436ee5'
down_revision = '6aaecffa0437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_link', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_class', schema=None) as batch_op:
        batch_op.drop_column('meet_link')

    # ### end Alembic commands ###
