"""empty message

Revision ID: b42c3cec2144
Revises: 72a89d6d107d
Create Date: 2025-01-28 14:35:06.684919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42c3cec2144'
down_revision = '72a89d6d107d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('teacher', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_constraint('virtual_class_class_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('virtual_class_teacher_id_fkey', type_='foreignkey')
        batch_op.drop_column('link')
        batch_op.drop_column('class_id')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('virtual_class_teacher_id_fkey', 'teacher', ['teacher_id'], ['id'])
        batch_op.create_foreign_key('virtual_class_class_id_fkey', 'class', ['class_id'], ['id'])
        batch_op.drop_column('price')
        batch_op.drop_column('capacity')
        batch_op.drop_column('teacher')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
