"""empty message

Revision ID: d77df8481d01
Revises: e7d825267ae4
Create Date: 2025-01-23 02:12:01.599990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77df8481d01'
down_revision = 'e7d825267ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('teacher', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('dayOfWeek', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('startTime', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('endTime', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('enrolled', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('schedule_class_id_fkey', type_='foreignkey')
        batch_op.drop_column('day')
        batch_op.drop_column('end_time')
        batch_op.drop_column('class_id')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('day', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('schedule_class_id_fkey', 'class', ['class_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('enrolled')
        batch_op.drop_column('capacity')
        batch_op.drop_column('endTime')
        batch_op.drop_column('startTime')
        batch_op.drop_column('dayOfWeek')
        batch_op.drop_column('teacher')
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
