"""empty message

Revision ID: e1534138f638
Revises: dd212125cf6f
Create Date: 2025-01-23 16:41:48.021793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1534138f638'
down_revision = 'dd212125cf6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('events_selection', sa.String(length=120), nullable=False),
    sa.Column('parent_name', sa.String(length=120), nullable=False),
    sa.Column('special_request', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
