"""empty message

Revision ID: e2dc4dc692ac
Revises: 55598dbe95ad
Create Date: 2025-02-11 17:54:27.675144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2dc4dc692ac'
down_revision = '55598dbe95ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('class_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.drop_constraint('enrollment_class_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('enrollment_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('class_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('parent_payment', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_payment', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('enrollment_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('enrollment_class_id_fkey', 'class', ['class_id'], ['id'])
        batch_op.drop_column('price')
        batch_op.drop_column('class_name')
        batch_op.drop_column('child_name')

    # ### end Alembic commands ###
